export const APP_VERSION = "0.2.5";
export const PROTOCOL_VERSION = 4;
export const VIEWER_ID_HEADER = "x-rvw-viewer-id";

export const GIT_OBJECT_ID_PATTERN = /^[0-9a-f]{40,64}$/i;

export const MAX_TEXT_DOCUMENT_BYTES = 1024 * 1024;
export const MAX_MARKDOWN_ASSET_BYTES = 5 * 1024 * 1024;
export const MAX_GITHUB_ATTACHMENT_BYTES = 10 * 1024 * 1024;
export const MAX_GITHUB_ATTACHMENT_STDERR_BYTES = 64 * 1024;
export const GITHUB_ATTACHMENT_TIMEOUT_MS = 30_000;
export const MAX_COMMENT_BODY_BYTES = 64 * 1024;
export const MAX_AUTHOR_LABEL_CHARACTERS = 100;
export const MAX_IDEMPOTENCY_KEY_CHARACTERS = 200;
export const DEFAULT_PULL_REQUEST_LIST_LIMIT = 50;
export const MAX_PULL_REQUEST_LIST_LIMIT = 100;
export const DEFAULT_COMMENT_LIST_LIMIT = 50;
export const MAX_COMMENT_LIST_LIMIT = 100;
export const DEFAULT_COMMENT_WATCH_LIMIT = 100;
export const MAX_COMMENT_WATCH_LIMIT = 100;
export const DEFAULT_COMMENT_WATCH_INTERVAL_SECONDS = 10;
export const MAX_COMMENT_WATCH_INTERVAL_SECONDS = 300;
export const MAX_COMMENT_LIST_BODY_PREVIEW_BYTES = 512;
export const MAX_CODE_REFERENCES = 200;
export const MAX_CODE_REFERENCE_LABEL_CHARACTERS = 200;
export const MAX_CODE_REFERENCE_PATH_CHARACTERS = 4_096;
export const MAX_CODE_REFERENCE_DESCRIPTION_CHARACTERS = 1_000;
export const MAX_WALKTHROUGH_BODY_BYTES = 256 * 1024;
export const MAX_WALKTHROUGH_TITLE_CHARACTERS = 200;
export const MAX_SEARCH_QUERY_BYTES = 1024;
export const MAX_SEARCH_RESULTS = 500;
export const MAX_SEARCH_STDOUT_BYTES = 8 * 1024 * 1024;

export const DEFAULT_PROCESS_TIMEOUT_MS = 30_000;
export const DEFAULT_PROCESS_STDOUT_BYTES = 16 * 1024 * 1024;
export const DEFAULT_PROCESS_STDERR_BYTES = 2 * 1024 * 1024;
